### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by Kohulan** [hannbus/ChemIcal-DatasEt-comparatoR#12]
Hey @hannbus ,

Could you rename the repository to match the name on Read-Me? ChemIcal DatasEt comparatoR (CIDER)

Thanks

**Comment by hannbus** [comment]
I changed it the way you wrote it but when renaming it changed the spaces and the brackets to dashes. Is it okay like that or should I change it again?

**Comment by Kohulan** [comment]
It should look like the: "ChemIcal-DatasEt-comparatoR"

**Comment by hannbus** [comment]
Okay, I changed it accordingly,

**Comment by Kohulan** [comment]
Great, Thanks a lot 😄
