### ISSUE TITLE
README.md adjustments

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal-DatasEt-comparatoR#14]
- In readme, Python 3.8 needs to be updated to Python 3.10
- White backgrounds for logos in readme?
- Why is the logo in the workflow dir? Is there a better place for it? Place it in repo root dir

**Comment by JonasSchaub** [comment]
Maybe suggest a more simple name for the conda environment in the readme.

**Comment by JonasSchaub** [comment]
Also, we could tell people to run pytest after the CIDER setup to check whether everything works.

**Comment by Kohulan** [comment]
I think we can close this issue now. @JonasSchaub ?
