### ISSUE TITLE
AttributeError in chemical_space_visualization from _t_sne.py

### ISSUE THREAD

**Issue by hannbus** [hannbus/ChemIcal-DatasEt-comparatoR#19]
When plotting the chemical space visualization with tsne as dimension reduction method in a notebook, an AttributeError is raised from sklearn\manifold\_t_sne.py. It says "AttributeError: 'list' object has no attribute 'shape'". For the other dimension reduction methods the chemical space visualization works well. Any ideas what the problem is?

**Comment by OBrink** [comment]
Sorry for the late reply.
I cannot replicate the problem. Are we talking about this line in the notebook?
`cider.chemical_space_visualization(testdict, dimension_reduction = 'tsne', interactive = False, fp_bits = 1024, fp_radius = 2)`
I am getting the following plot: 
![image](https://user-images.githubusercontent.com/59618901/188199053-7b356982-c3b2-4f6b-a8ce-e8e5b4ff1138.png)
@JonasSchaub @Kohulan, can you reproduce the problem, or have I done something weird with my environment?


#### The error message:
* "AttributeError: 'list' object has no attribute 'shape'" indicates that the method is expecting a numpy array and is getting a list. 
* For reproduction:
    ```
    test_array = np.array([[1,2,3],[4,5,6]])
    test_array.shape
    >> (2, 3)
    ```
* A list in Python does have the *shape* attribute: 
    ```
    test_list = [[1,2,3],[4,5,6]]
    test_list.shape
    >> AttributeError: 'list' object has no attribute 'shape'
    ```
The function is expecting an array and is getting a list. That causes the error.

**Comment by JonasSchaub** [comment]
I also tried to reproduce the problem (on the latest commit of dev-Hannah, https://github.com/hannbus/ChemIcal-DatasEt-comparatoR/commit/d339471dabaeffc33b0469173ef90538e1386d85) but it worked fine for me (same as Otto).

@hannbus , maybe a "clean re-install" of your conda environment could help? Or maybe Otto and I have to do that.

**Comment by hannbus** [comment]
I created a complete new conda environment and installed everything anew. But I still get the same error when trying to run the cell in the notebook. Do you have any ideas what else to do?

**Comment by OBrink** [comment]
The unit test sheds light on what is happening:

```
self = TSNE(perplexity=2)
X = [[0, 0, 0, 0, 0, 0, ...], [1, 0, 0, 0, 0, 0, ...], [0, 1, 0, 0, 0, 0, ...], [1, 0, 0, 0, 0, 0, ...], [0, 1, 0, 0, 0, 0, ...], [0, 0, 0, 0, 1, 0, ...], ...]

    def _check_params_vs_input(self, X):
>       if self.perplexity >= X.shape[0]:
E       AttributeError: 'list' object has no attribute 'shape'
```

First, X is declared as a list. Then, the method tries to access X.shape. This is a proper bug in scikit-learn. Can we update it?

**Comment by JonasSchaub** [comment]
I have scikit-learn version 1.1.2 installed and that seems to be the latest version. So the question seems to be rather: Can we downgrade scikit-learn?

**Comment by JonasSchaub** [comment]
I have downgraded scikit-learn to version 1.1.1 and the tsne chemical space plot is working! Also, the whole notebook and and all tests are working. Can you guys confirm this?

**Comment by OBrink** [comment]
We did the same thing parallely! 👯 
running `pip install scikit-learn==1.1.1` in the environment where it does not work, fixed it for me.

**Comment by JonasSchaub** [comment]
@hannbus can you confirm?

In that case, it would be just a matter of specifying scikit-learn v1.1.1 in the setup.py, right?

**Comment by OBrink** [comment]
I have specified the version in the setup.py file.
@hannbus: Could you confirm that it works and close the issue?

**Comment by JonasSchaub** [comment]
The tests failed due to an invalid scikit-learn version(?)...

**Comment by OBrink** [comment]
The test failed because scikit-learn==1.1.1 requires at least Python 3.8

**Comment by OBrink** [comment]
@Kohulan @JonasSchaub @hannbus 
Why is it still failing? I removed Python 3.7 as a test environment in the tox.ini, but it still tries to build the Python 3.7 environment? Did I do something wrong?

**Comment by OBrink** [comment]
For the future: 
* The workflow Python version is defined in [.github](https://github.com/hannbus/ChemIcal-DatasEt-comparatoR/tree/main/.github)/[workflows](https://github.com/hannbus/ChemIcal-DatasEt-comparatoR/tree/main/.github/workflows)/main.yml
* 3.1, 3.2, etc can be specified as float numbers. If you try to define version 3.10, it needs to be specified as "3.10"

**Comment by OBrink** [comment]
Finally, it's all passing again. Please check and close the issue :)

**Comment by Kohulan** [comment]
I can confirm that everything is working fine on my end. :)

**Comment by JonasSchaub** [comment]
For me, too! The whole notebook and all tests are working. I only get two warnings when running the tests but that is why @OBrink opened #30, right?
And @hannbus if you can confirm that everything is working, could you comment in the tsne cell in the workflow notebook again?

**Comment by Kohulan** [comment]
@JonasSchaub I made a pull request with the updated notebook. Merge it before @hannbus starts some more additional work.

**Comment by hannbus** [comment]
The downgrading solved the issue for me as well. I'll wait for the merge before doing the other things.
