### ISSUE TITLE
PDF export in the Workflow notebook is not working

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal-DatasEt-comparatoR#24]
Branch: dev-Hannah
Commit: https://github.com/hannbus/ChemIcal-DatasEt-comparatoR/commit/d339471dabaeffc33b0469173ef90538e1386d85
@hannbus 

In the Workflow notebook, the last cell ``cider.export_all_picture_pdf()`` is not working.
Output:

````
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [35], in <cell line: 1>()
----> 1 cider.export_all_picture_pdf()

AttributeError: 'ChemicalDatasetComparator' object has no attribute 'export_all_picture_pdf'
````

I guess the function call in the notebook has to be updated to ``export_all_figures_pdf()`` as it is now in the cider.py file.

**Comment by hannbus** [comment]
This also works now on my branch. Can I close the issue?

**Comment by Kohulan** [comment]
Make a pull request and let @JonasSchaub test and confirm after that we can close the issue.

**Comment by JonasSchaub** [comment]
Yes, it works now, great!
