### ISSUE TITLE
Catch warnings

### ISSUE THREAD

**Issue by OBrink** [hannbus/ChemIcal-DatasEt-comparatoR#30]
* Catch warnings specifically where they are produced using the warnings.catch_warnings() context manager
* There are a couple of FutureWarnings:
    ´´´
    =============================== warnings summary ===============================
    Tests/test_functions.py::test_chemical_space_plot_tsne
    /home/runner/work/ChemIcal-DatasEt-comparatoR/ChemIcal-DatasEt-comparatoR/.tox/py310/lib/python3.10/site-packages/sklearn/manifold/_t_sne.py:795: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
    ´´´
* [Full example about this from StackOverflow](https://stackoverflow.com/questions/3920502/how-to-suppress-a-third-party-warning-using-warnings-filterwarnings):

    ```python
    import warnings

    # Custom warning class for the example
    class MyWarning(UserWarning):
        pass

    def function_that_raises_warning(num):
        print(num)
        warnings.warn("This is a warning", MyWarning)


    with warnings.catch_warnings():
        function_that_raises_warning(1) # raises warning
        warnings.filterwarnings(
            action="ignore", category=MyWarning, message="This is a warning"
        )
        function_that_raises_warning(2) # Warning is filtered
    function_that_raises_warning(3) # raises warning
    ```

**Comment by OBrink** [comment]
or define the parameter specifically instead of catching the warning

**Comment by hannbus** [comment]
I tried setting the parameters to what they suggested in the warning, but this resulted in the AttributeError we saw before with the TSNE (#19). In this case I can only catch the warnings as @OBrink suggested, right?

**Comment by OBrink** [comment]
I would suggest to set the parameter to "random" or to catch the warning

**Comment by JonasSchaub** [comment]
I guess we have to try it with random then. Because using the default and catching the warning might lead to problems with the next update of the library because then pca will be used as default which leads to the AttributeError. Do I get this right?

**Comment by hannbus** [comment]
Yes, you got it right. But actually, we are already using an old version of scikit-learn. We specified the version to 1.1.1 with the old default values leading to the warnings. In the most recent version (which we used some time ago) the default values have been changed according to the warnings, which seem to cause the AttributeError.

**Comment by JonasSchaub** [comment]
Ok, but using "random" does not cause a warning or an error?

**Comment by hannbus** [comment]
Yes, with the old default parameters (learning_rate=200.0, init='random') the TSNE works and if thoses parameters are set explicitly there are no warnings when running the unit tests.

**Comment by JonasSchaub** [comment]
Wonderful, then this is our way to go, I would say.

**Comment by JonasSchaub** [comment]
Can this now be closed?

**Comment by hannbus** [comment]
Yes, it can.
