### ISSUE TITLE
Test CIDER Workflow with COCONUT SDF

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal-DatasEt-comparatoR#34]
Similar to #29, we should test the CIDER workflow notebook for the COCONUT SDF. For one, because it is a nice case study for a relevant data set that is already interesting when it is not compared to another data set (-> next step), and also, it would be good to test CIDER on a bigger data set like COCONUT to identify (and tag in the comments) the methods that scale unfavorably with the dataset size, like e.g. get_duplicate_key() where every molecule is tested against every other molecule. The COCONUT SDF can be downloaded here: https://coconut.naturalproducts.net/download

**Comment by JonasSchaub** [comment]
If the faulty molecules are deleted, e.g. the molecular weight plot works but it is definitely not suitable for this many molecules:
![image](https://user-images.githubusercontent.com/44881147/192295865-983ee18c-b79e-42de-af53-2dd2d8d3b7c8.png)

**Comment by hannbus** [comment]
Yes, I got the same problems and I will change the default value for the delete parameter in the import function to True.

**Comment by JonasSchaub** [comment]
@hannbus thank you!
Afterwards, we can discuss what else needs to be adapted for larger data sets like COCONUT.

**Comment by hannbus** [comment]
For the plotting you could change the image size to a larger value for the width. That makes the intervals a lot better to read.

**Comment by JonasSchaub** [comment]
![distribution_of_Molecular Weight](https://user-images.githubusercontent.com/44881147/193235856-b866c975-8703-4152-beb7-f2ce5da0568e.png)

Increasing the figsize parameters did not get me to where I wanted but increasing the bin width 10-fold did.
I guess in cases like this we can leave it to the user to play with the parameters, would you agree?

**Comment by hannbus** [comment]
I guess that should be fine. I also added some explanation for this in the notebook.

**Comment by JonasSchaub** [comment]
I am starting a new test run with the COCONUT SDF and CIDER now. 
First problem I habe faced: If I download the compressed COCONUT SDF from https://coconut.naturalproducts.net/download and unzip it (btw, why is it a tar ball as well? It is only one file in this archive and TAR does not give you any additional compression in addition to the zipping that is also done, does it?), put it into the data folder for the CIDER workflow (deleting all other files there), CIDER complains that there are no SDF in the folder. The reason: the file extension ".SDF" is written in upper-case letters. If I correct this, it works.

Question is: Should CIDER's check for SDF file extensions be case-insensitive? Or should the COCONUT SDF file extension actually be in lower-case letters instead?

**Comment by JonasSchaub** [comment]
Next problem is in code cell nr. 18 "cider.visualize_intersection(testdict)": It crashes because there is only one data set being analysed. There should be an if statement in the cell, so that it is only executed when there are two or more data sets being analysed.

**Comment by hannbus** [comment]
For the sdf file problem, I can change it so that 'SDF' and 'sdf' are recognized.
The problem in the workflow is also fixed.

**Comment by JonasSchaub** [comment]
I guess this would be good. CIDER-wise, we are on the safe side, then.
And thanks for the fix!

**Comment by JonasSchaub** [comment]
Next problem in cell 34 "cider.draw_most_frequent_scaffolds(testdict)": The output looks like this

![image](https://user-images.githubusercontent.com/44881147/201326197-5417ab75-7343-4b09-a54c-d9b0926dd956.png)

What bugs me is the empty first position, the other four scaffolds look alright (and also their frequency in an NP data set seems reasonable). I guess what happened is that the first position is an "empty" scaffolds, i.e. molecules having no rings. We know from similar analyses that about 5 % of the molecules in COCONUT are like that, so it would make sense that this appears as the most frequent "scaffold" here. But if that theory is correct, the display has to be adapted so that everyone understands what happened here.

**Comment by JonasSchaub** [comment]
The next problem is in the cell below:

![image](https://user-images.githubusercontent.com/44881147/201326953-62412c09-43e1-44eb-8bdc-cfdd635a5978.png)

Here, I guess it would be enough to try-except and log this exception, so that the whole analysis does not fail because of one (hopefully) faulty molecule.

**Comment by JonasSchaub** [comment]
As could have been expected, the same also happens in the cell below

![image](https://user-images.githubusercontent.com/44881147/201331519-63f089dd-012b-4fe9-a133-df159b993de9.png)

**Comment by JonasSchaub** [comment]
Ok, trying the chemical space visualization crashed my whole laptop again 🙈
Does anyone know how we can prevent this?

**Comment by hannbus** [comment]
The empty scaffold should come from molecules with no rings, as you said. I could test for rings in a first step, then exclude all molecules without rings for any further scaffold analysis and get a logging entry about the reduction of molecules for the scaffold analysis. Would this be an option? Or should they be included to get the frequency on non-ring molecules?

The KekulizeExceptions is something I got before. When generating the scaffold there seem to be some molecules that generate problematic frameworks. I thougt I solved this problem but there still seem to be problematic molecules. I will look what kind of molecule is causing the error and see how to solve it. If there is not good way to fix those molecules, would it be fine to exclude them?

For the shared molecules I would change it in CIDER itself.

**Comment by Kohulan** [comment]
> Ok, trying the chemical space visualization crashed my whole laptop again 🙈 Does anyone know how we can prevent this?

I am not sure whether we can prevent this because it tries to fill up the available memory. This should have been handled by windows but I think it is not happening so I won't suggest running the notebook would be a good idea on a laptop.

**Comment by hannbus** [comment]
About the problem with the scaffold: The molecules causing the error seem to be structures with a carbon atom with three bonds and a negative charge (e.g. CNP0109170 or CNP0082805). The problem with these molecules are due to Chem.Kekulize() in the method. When I try the Chem.Kekulize() on these molecule outside of the method it works just fine and afterwards it also magically works inside the method and there is no KekulizeException for this particular molecule anymore.
Actually, I don't know what the problem is or why it disappears when running on a single molecule. Does any of you have an idea?

**Comment by JonasSchaub** [comment]
> I could test for rings in a first step, then exclude all molecules without rings for any further scaffold analysis and get a logging entry about the reduction of molecules for the scaffold analysis. Would this be an option? Or should they be included to get the frequency on non-ring molecules?

- Well, in accordance with our scaffold paper that was published yesterday (https://jcheminf.biomedcentral.com/articles/10.1186/s13321-022-00656-x *cough, cough*), I would suggest including the linear molecules with no rings in the analysis, since this info is definitely interesting. But can you maybe create a meaningful depiction for them, i.e. a text saying "no scaffold/rings"?

> If there is not good way to fix those molecules, would it be fine to exclude them?
- Yes, definitely. Single molecules causing problems should just be skipped (and logged) in these analyses.

> For the shared molecules I would change it in CIDER itself.
- Yes, like for the intersection visualisation: An exception thrown by the CIDER method and in the notebook a preliminary check whether the method can be executed safely (because there are more than one data sets imported.

> I am not sure whether we can prevent this because it tries to fill up the available memory. This should have been handled by windows but I think it is not happening so I won't suggest running the notebook would be a good idea on a laptop.
- Yes, Jupyter notebook should not be able to use all the available memory. I will check whether I can assign a fixed heap space to the notebook server to prevent this.

> About the problem with the scaffold: The molecules causing the error seem to be structures with a carbon atom with three bonds and a negative charge (e.g. CNP0109170 or CNP0082805). The problem with these molecules are due to Chem.Kekulize() in the method. When I try the Chem.Kekulize() on these molecule outside of the method it works just fine and afterwards it also magically works inside the method and there is no KekulizeException for this particular molecule anymore.
Actually, I don't know what the problem is or why it disappears when running on a single molecule. Does any of you have an idea?
- Inside the method, is Kekulize() called after side chains have already been removed to create the scaffold? This could be the issue because then, all the valences are screwed up anyway. If you run it prior to generating scaffolds, bond orders can be assigned correctly because the molecule is still "intact" and the later Kekulize() call within the method probably only checks for the presence of the bond orders, not whether they still make sense.
I see two possible solutions: Wrapping the respective line in a try-except block (reasonable because we know which error we are looking for and kekulization is always an issue) or kekulizing all input molecules at the very beginning as an additional way to filter out the faulty ones.

**Comment by JonasSchaub** [comment]
On the memory and laptop-crashing problem with the chemical space visualization:
I now tried running the Jupyter notebook server like this 
`jupyter notebook --NotbookApp.iopub_Data_Rate_Limit=1e6 --NotebookApp.max_buffer_size=1000000` 
setting a fixed maximum "data rate" and "buffer size". I have no idea whether that actually limits the memory the notebook server can use as I want to. Actually, I think it does not because with these configurations, it should only allocate up to 1 MB of RAM if I understand the doc correctly but it definitely allocates more.
Nevertheless, the chemical space visualization did not crash my laptop this time but instead produced a memory error as it is supposed to:

![image](https://user-images.githubusercontent.com/44881147/201882237-ba1b9d06-135c-4dbb-b101-78937657e785.png)

Any further ideas on this? I will test it again without the params under similar conditions but it is not a "very exact science", these test runs... 
Maybe in the end, we can only add a warning to the doc/notebook that these methods with large data sets will run into memory issues and might crash the machine in the process...

**Comment by JonasSchaub** [comment]
Ok, update, now I also got the memory error without the additional params when starting the notebook server. It did not crash my laptop this time. So I don't know whether they actually had an effect before.

Maybe, we can put a note in the notebook like this (critics welcome):

"Note: The chemical space visualization is a very time- and memory-intensive process and scales unfavorably with the data set size. Especially memory can become a problem when the workflow is executed with a large data set on a standard laptop. 
The developers of ChemPlot report benchmark analyses that went through on a machine with 8 GB RAM for data set sizes up to 41,000 structures (https://doi.org/10.1002/cmtd.202200005). An analysis using CIDER on 400,000 natural product structures taken from the COCONUT database (https://coconut.naturalproducts.net) on a machine with 16 GB of RAM available failed with a MemoryError."

**Comment by JonasSchaub** [comment]
Another note on this: With 51k ChEBI molecules, the chemical space visualization works on my laptop.

**Comment by hannbus** [comment]
For the no-ring molecules: I could at a CH4 as image and put the no rings/scaffold text beneath. Without any molecular structure it will not and only test is not an option as well (at least as far as I tried). Would the CH4 solution be an option?

For the kekulize problem: @JonasSchaub was right, if the molecules are kekulized before the getting the very first scaffold generation, there is no problem later. When all molecules are kekulize at the beginning (either while importing or before scaffold analysis), there should be no need to exclude them with a try-except block, right?

**Comment by hannbus** [comment]
Using the '*' works fine, thanks!
