### ISSUE TITLE
Depictions without coordinates

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal-DatasEt-comparatoR#45]
I have imported an SD file without any atom coordinates into CIDER and it plots all atoms on top of each other:

![image](https://user-images.githubusercontent.com/44881147/213443136-bb334825-88ee-43a4-bb88-08538be00058.png)

This is the file: 
[COCONUT_1000_subset.txt](https://github.com/hannbus/ChemIcal-DatasEt-comparatoR/files/10456697/COCONUT_1000_subset.txt)

Is there a way we could fix that, i.e. detect whether there are or there aren't coordinates given in the input SD files?

@hannbus @OBrink @Kohulan

**Comment by OBrink** [comment]
According to [this](https://www.rdkit.org/docs/GettingStartedInPython.html), RDKit allows you to generate the coordinates using its AllChem module

Assuming _mol_ is a mol object:
```
from rdkit.Chem import AllChem
AllChem.Compute2DCoords(mol)
```

But I don't know how to check it in an efficient way. I guess you could get the coordinates for the first atom and check whether they are (0, 0). If that's the case, you could generate the coordinates.

**Comment by JonasSchaub** [comment]
Small remark, the first atom could in fact be placed at (0,0,0) as the central reference point for the other atoms. So maybe by checking the first two atoms, we could be sure.

**Comment by hannbus** [comment]
I added some lines to check if a molecule has valid coordinates in the SD file and calculate them if necessary. Now the atoms are not plotted on top of each other anymore.
