### ISSUE TITLE
Update PDF report export function name in workflow notebook

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal-DatasEt-comparatoR#46]
In the workflow notebook, the last cell tries to use the old method for the PDF report export, which has been renamed to export_figure_report(). Please update.

**Comment by hannbus** [comment]
It is now renamed and works.

**Comment by Kohulan** [comment]
@hannbus Could you make the pull request?

**Comment by JonasSchaub** [comment]
Maybe wait until all my "small issues" are completed.

**Comment by Kohulan** [comment]
Yes agreed. That would be good.
