### ISSUE TITLE
PDF report layout errors

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal-DatasEt-comparatoR#47]
First of all, the PDF report has definitely improved greatly and I am very happy about it!

But there are some layout problems in the report file I generated: 
[cider_report.pdf](https://github.com/hannbus/ChemIcal-DatasEt-comparatoR/files/10677130/cider_report.pdf)

Most of the figures (molecules plots and chemical space plots) are missing their right half. 

And very minor: On the first page, maybe you could fit "Generated CIDER keys" and figures into a single line in the table? Maybe simply remove the "CIDER" here. And there could be a little more space between the bar plots.

Apart from that, I'm really happy!

**Comment by hannbus** [comment]
The figures should be now be complete. 
After deleting CIDER the table has now singel lines for the first column.
Each plot or image has now its own page, so there is a lot space between the bar plots as well :)

**Comment by JonasSchaub** [comment]
Yes, I can confirm all of that, thank you!
