### ISSUE TITLE
Update fpdf version in Python_Requirements.txt

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal-DatasEt-comparatoR#48]

**Comment by hannbus** [comment]
The version of FDPF is what I use. I will add FPDF2 and the version from my conda environment?

**Comment by Kohulan** [comment]
Yes that would be fine.

**Comment by JonasSchaub** [comment]
I just noticed that the fpdf version in setup.py has been updated but not the one in python_requirements.txt. They should be the same, right? Does the latter text file any purpose, anyway?

**Comment by Kohulan** [comment]
For a person who does not wish to install CIDER through pip, they can use the python_requirements.txt to install the dependencies.

**Comment by JonasSchaub** [comment]
Ah, thank you. So it is just a formality but we should keep it up to date.

**Comment by Kohulan** [comment]
@hannbus on your branch there are two FPDF versions, Please remove the version with 1.7 ..

**Comment by hannbus** [comment]
One is FPDF and the other one is FPDF2 (I forgot the 2 and added it now). I will leave both of them there?

**Comment by JonasSchaub** [comment]
Do you still use FPDF(1)? You have removed it in setup.py

**Comment by hannbus** [comment]
FPDF(1) is actually not used anymore. I will remove it.

**Comment by JonasSchaub** [comment]
Thank you!
