### ISSUE TITLE
Logging - create a new log file for a new run of CIDER

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal-DatasEt-comparatoR#49]
The logging functionality just appends everything to the log file if there is one already existing in the output folder. This file can then become very big and cluttered. It would be better to create a new one, e.g. at data import where there is also the warning that old outputs will be overwritten. Alternatively, you could create a log file with a time stamp in its name and not delete the old log file. Maybe better this way, but the log files should be moved to their own folder within the output folder then.

**Comment by hannbus** [comment]
I can get a new log file with a time stamp for every time the notebook is restarted. But I am not sure, how to hinge the new log file on the data import, as I create the log file as the very first action even before the import.

**Comment by JonasSchaub** [comment]
If you create a new log file for every run, you can do that as you do it now.

**Comment by JonasSchaub** [comment]
Afterwards, create a pull request

**Comment by Kohulan** [comment]
Solved with #50
