### ISSUE TITLE
Reduce default FP size in chemical space visualization

### ISSUE THREAD

**Issue by Kohulan** [hannbus/ChemIcal-DatasEt-comparatoR#55]
Have a look at this first:
https://greglandrum.github.io/rdkit-blog/posts/2023-03-26-fingerprint-size-and-similarity-searching1.html

I would suggest let's set the FP size to 512 or lower as a default value.

**Comment by JonasSchaub** [comment]
TL;DR: The default fingerprint size that we are using for the chemical space visualisations (2048) is quite big and therefore, the chemical space visualisations take very long, especially with bigger datasets. But according to that blog post by Greg Landrum, a fingerprint size of 512 (or even lower) should still be sufficient for an application such as this. And it would speed up the calculations considerably, most likely.

**Comment by Kohulan** [comment]
I have created two plots with different fingerprints (1024 and 256) as suggested by @OBrink. The use of 1024 bits for generating fingerprints is overkill and is not necessary for larger datasets in my opinion so we should set the default FP size to 512 or lower. If there any objections? 

FP: 1024
![image](https://user-images.githubusercontent.com/30716951/228785785-93f8d5d7-b07a-4af1-827e-f49049c3917e.png)

FP: 256
![image](https://user-images.githubusercontent.com/30716951/228792164-5c5403ed-1e82-499e-827e-32fb02115e00.png)

**Comment by OBrink** [comment]
Based on these plots, I don't see any reason to work with the larger fingerprints. Then let's go for the fingerprints with a length of 512

**Comment by Kohulan** [comment]
I and @JonasSchaub decided that this section needs further discussion. It looks like there is no effect when using different fingerprints.
Line 1618 - 1627 doesn't do anything!
```python
        if fp_radius != 2 or fp_bits != 2048:
            if all_mols_list[0].startswith("InChI="):
                new_fingerprint = descriptors.get_ecfp_from_inchi(
                    all_mols_list, target_list, radius=fp_radius, nBits=fp_bits
                )
            else:
                new_fingerprint = descriptors.get_ecfp(
                    all_mols_list, target_list, radius=fp_radius, nBits=fp_bits
                )
            chem_space._Plotter__mols = new_fingerprint[0]
```
The line ```chem_space._Plotter__mols = new_fingerprint[0]``` is also wrong.


Looking at the chemplot code, the moment you call ```def from_inchi(cls, inchi_list, target=[], target_type=None, sim_type=None):```
it is always going to return a **Plotter** object with generated fingerprint size of 2048.

**code block:**

```python

    def from_inchi(cls, inchi_list, target=[], target_type=None, sim_type=None):
        """
        Class method to construct a Plotter object from a list of InChi.
        
        :param inchi_list: List of the InChi representation of the molecules to plot.
        :type inchi_list: dict
        :param target: target values
        :type target: dict
        :param target_type: target type R (regression) or C (classificatino)
        :type target_type: string
        :param sim_type: similarity type structural or tailored 
        :type sim_type: string
        :returns: A Plotter object for the molecules given as input.
        :rtype: Plotter
        """
                
        return cls(inchi_list, target, target_type, sim_type, desc.get_mordred_descriptors_from_inchi, desc.get_ecfp_from_inchi)
        
 ```
 **desc.get_ecfp_from_inchi**
 
 ```python
def get_ecfp_from_inchi(inchi_list, target_list, radius=2, nBits=2048):
    """
    Calculates the ECFP fingerprint for given InChi list
    
    :param inchi_list: List of InChi
    :param radius: The ECPF fingerprints radius.
    :param nBits: The number of bits of the fingerprint vector.
    :type inchi_list: list
    :type radius: int
    :type nBits: int
    :returns: The calculated ECPF fingerprints for the given InChi
    :rtype: Dataframe
    """  
    
    return generate_ecfp(inchi_list, Chem.MolFromInchi, 'InChi', target_list, radius, nBits)
 ```

**Comment by JonasSchaub** [comment]
The way we see it, there is no way, actually, to set a different fingerprint size in chemplot. We also opened an issue in their repository: https://github.com/mcsorkun/ChemPlot/issues/18 

The statement that "The line chem_space._Plotter__mols = new_fingerprint[0] is also wrong." was actually tested because the plots looked the same with a set fingerprint size of 5. 

@hannbus could you maybe tell us how you came up with this line? Did you get it from somewhere?

**Comment by hannbus** [comment]
I actually found the same problem yesterday and am looking for a way to fix it. 
The fingerprint values can be changed by setting the default values for generate_ecfp to a new value. The fingerprint than has a different size. The problem is that the Plotter imports the descriptor module (which includes generate_ecfp) and the changed default values are not taken on, as I assume. 
About I came up with this, I am not sure because it was some time ago, but I think I took a look at the repository. Apparently, I should have given this a more in-depth look, to avoid this mistake. Sorry for this issue.

**Comment by JonasSchaub** [comment]
> The fingerprint values can be changed by setting the default values for generate_ecfp to a new value.

Well, yes, but that is a private method called by the constructor of that class, if I am not mistaken. 

But nothing to be sorry about!
