### ISSUE TITLE
Switch Lipinski rule violations to RDKit-native functionality?

### ISSUE THREAD

**Issue by JonasSchaub** [hannbus/ChemIcal-DatasEt-comparatoR#59]
See Kohulans issue on the RDKit repo: https://github.com/rdkit/rdkit/discussions/6180#discussioncomment-5847170

**Comment by Kohulan** [comment]
We could use all Lipinski modules?
Ex: Lipinski.NumHAcceptors(mol)

**Comment by JonasSchaub** [comment]
Would probably be better if we speak of the Lipinski rule of five.
