### ISSUE TITLE
Use identifier or position in SD file to report duplicates

### ISSUE THREAD

**Issue by OBrink** [hannbus/ChemIcal-DatasEt-comparatoR#62]

**Comment by hannbus** [comment]
I fixed the duplicate method and added the index as additional information for the duplicate. But the index might not be equivalent with the index in the SD file as there can be molecules declared as invalid and removed from the analysis while importing. Therefore, there might be a slight difference between the indeces in the SD file and the indeces used in the working dataframe. Should I change this?

**Comment by JonasSchaub** [comment]
I guess the SDMolSupplier objects should be our points of reference here. And the molecules declared as invalid are removed from those right? This means that I could use SDMolSupplier.getItemText(index) or SDMolSupplier.moveTo(index) with the indices that you are giving right now to retrieve the specific molecules, right? If we can be sure on that (maybe test it to be sure) and declare it this way in the documentation, I would vote for this course of action.

Please correct me if I'm wrong at any point.

And thank you for the fix!

**Comment by hannbus** [comment]
It does work just using SDMolSupplier[index]. 

Please do not close this issue, as I still need to add a proper unit test!

**Comment by JonasSchaub** [comment]
Could you also adjust and document this in the workflow notebook, please? :)

**Comment by hannbus** [comment]
Yes, will do!
