### ISSUE TITLE
Fix duplicate search

### ISSUE THREAD

**Issue by OBrink** [hannbus/ChemIcal-DatasEt-comparatoR#67]
Use hashmap (dictionary) for a fast search

**Comment by JonasSchaub** [comment]
It seems to be working to me but maybe, a more python-experienced person than me should also take a look at it.

Is the "identifier" parameter unused now on purpose? If yes, please remove it.

**Comment by JonasSchaub** [comment]
```
mol_index = -1
mol_list = []
duplicate_list = []
duplicate_index = []
for mol in all_dicts[single_dict][self.identifier_keyname]:
    mol_index += 1
    if mol not in mol_list:
        mol_list.append(mol)
    else:
        duplicate_list.append(mol)
        duplicate_index.append(mol_index)
```

Again, one of our Python developers should check my claims, but: What you are using here is a list, right? This means that the line "if mol not in mol_list:" conducts an iterative search of the whole list for "mol". The lookup time increases with the list size this way and that is bad for us when we analyse big datasets. What we need, is a hashed collection which basically conducts this lookup in constant time / a single operation (its a little magic, we can tell you more about it if you want). If understand this post here correctly, the collection type to use in Python for this would be set() (or a dictionary): https://stackoverflow.com/questions/48073380/hashsets-and-hashtables-in-python

**Comment by JonasSchaub** [comment]
Dear @hannbus ,
thanks for adjusting that but you still have some unfavourably scaling steps in there. 

```
duplicate_list = []
count = collections.Counter(all_dicts[single_dict][self.identifier_keyname])
for mol in count:
    if count[mol] > 1:
        duplicate_list.append(mol)
all_dicts[single_dict][self.duplicates_keyname] = len(duplicate_list)
all_dicts[single_dict][self.duplicates_id_keyname] = duplicate_list
all_dicts[single_dict][self.duplicates_index_keyname] = []
for duplicate in duplicate_list:
    index_list = []
    for index, mol in enumerate(all_dicts[single_dict][self.identifier_keyname]):
        if mol == duplicate:
            index_list.append(index)
    all_dicts[single_dict][self.duplicates_index_keyname].append(index_list)
```

We first iterate over the identifier list to create the counter, then again to find those ids with count > 1, and then again for every identified duplicate to get the indices. The last steps scales especially unfavourably (number of duplicates times number of molecules).

I would propose the following method:

- initialise a dict with the molecule identifiers as keys and lists of their respective indices as values
- initialise a list or set for the ids of duplicate molecules
- iterate the molecule identifiers once to fill the dict
- if id is not yet in dict keys, add it to keys and its index as the only element in a new list as value
- if id is already in dict, retrieve the list of indices for that id and add the index of your current id/molecule to it; also, add the id to the duplicates list/set (if it is not already there! Probably a set would be better to ensure this)
- In the end, you can retrieve the indices of the duplicates in the set from the dict in a constant look-up time.

All in all, the id list if iterated once, plus a constant time look-up for every duplicate.

What do you think?

P.S.: Sorry for nagging so much about such details, but when you e.g. analyse collections like ChEMBL with more than 2 mio. compounds, it actually makes a significant difference.

**Comment by hannbus** [comment]
I changed it now according to what you wrote @JonasSchaub . Maybe check again, if it is finally okay.
